package com.sjy.equipment_manager_system.mbg.model;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   首页推荐专题表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table recommend_subject
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RecommendSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_subject.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_subject.subject_id
     *
     * @mbg.generated
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_subject.subject_name
     *
     * @mbg.generated
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_subject.recommend_status
     *
     * @mbg.generated
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_subject.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_subject.id
     *
     * @return the value of recommend_subject.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_subject.id
     *
     * @param id the value for recommend_subject.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_subject.subject_id
     *
     * @return the value of recommend_subject.subject_id
     *
     * @mbg.generated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_subject.subject_id
     *
     * @param subjectId the value for recommend_subject.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_subject.subject_name
     *
     * @return the value of recommend_subject.subject_name
     *
     * @mbg.generated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_subject.subject_name
     *
     * @param subjectName the value for recommend_subject.subject_name
     *
     * @mbg.generated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_subject.recommend_status
     *
     * @return the value of recommend_subject.recommend_status
     *
     * @mbg.generated
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_subject.recommend_status
     *
     * @param recommendStatus the value for recommend_subject.recommend_status
     *
     * @mbg.generated
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_subject.sort
     *
     * @return the value of recommend_subject.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_subject.sort
     *
     * @param sort the value for recommend_subject.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}