package com.sjy.equipment_manager_system.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMaintainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public TMaintainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeIsNull() {
            addCriterion("msubmit_time is null");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeIsNotNull() {
            addCriterion("msubmit_time is not null");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeEqualTo(Date value) {
            addCriterion("msubmit_time =", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeNotEqualTo(Date value) {
            addCriterion("msubmit_time <>", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeGreaterThan(Date value) {
            addCriterion("msubmit_time >", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("msubmit_time >=", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeLessThan(Date value) {
            addCriterion("msubmit_time <", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeLessThanOrEqualTo(Date value) {
            addCriterion("msubmit_time <=", value, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeIn(List<Date> values) {
            addCriterion("msubmit_time in", values, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeNotIn(List<Date> values) {
            addCriterion("msubmit_time not in", values, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeBetween(Date value1, Date value2) {
            addCriterion("msubmit_time between", value1, value2, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitTimeNotBetween(Date value1, Date value2) {
            addCriterion("msubmit_time not between", value1, value2, "msubmitTime");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleIsNull() {
            addCriterion("msubmit_people is null");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleIsNotNull() {
            addCriterion("msubmit_people is not null");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleEqualTo(String value) {
            addCriterion("msubmit_people =", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleNotEqualTo(String value) {
            addCriterion("msubmit_people <>", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleGreaterThan(String value) {
            addCriterion("msubmit_people >", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("msubmit_people >=", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleLessThan(String value) {
            addCriterion("msubmit_people <", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleLessThanOrEqualTo(String value) {
            addCriterion("msubmit_people <=", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleLike(String value) {
            addCriterion("msubmit_people like", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleNotLike(String value) {
            addCriterion("msubmit_people not like", value, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleIn(List<String> values) {
            addCriterion("msubmit_people in", values, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleNotIn(List<String> values) {
            addCriterion("msubmit_people not in", values, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleBetween(String value1, String value2) {
            addCriterion("msubmit_people between", value1, value2, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andMsubmitPeopleNotBetween(String value1, String value2) {
            addCriterion("msubmit_people not between", value1, value2, "msubmitPeople");
            return (Criteria) this;
        }

        public Criteria andErrorEquipIsNull() {
            addCriterion("error_equip is null");
            return (Criteria) this;
        }

        public Criteria andErrorEquipIsNotNull() {
            addCriterion("error_equip is not null");
            return (Criteria) this;
        }

        public Criteria andErrorEquipEqualTo(String value) {
            addCriterion("error_equip =", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipNotEqualTo(String value) {
            addCriterion("error_equip <>", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipGreaterThan(String value) {
            addCriterion("error_equip >", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipGreaterThanOrEqualTo(String value) {
            addCriterion("error_equip >=", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipLessThan(String value) {
            addCriterion("error_equip <", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipLessThanOrEqualTo(String value) {
            addCriterion("error_equip <=", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipLike(String value) {
            addCriterion("error_equip like", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipNotLike(String value) {
            addCriterion("error_equip not like", value, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipIn(List<String> values) {
            addCriterion("error_equip in", values, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipNotIn(List<String> values) {
            addCriterion("error_equip not in", values, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipBetween(String value1, String value2) {
            addCriterion("error_equip between", value1, value2, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorEquipNotBetween(String value1, String value2) {
            addCriterion("error_equip not between", value1, value2, "errorEquip");
            return (Criteria) this;
        }

        public Criteria andErrorDescrIsNull() {
            addCriterion("error_descr is null");
            return (Criteria) this;
        }

        public Criteria andErrorDescrIsNotNull() {
            addCriterion("error_descr is not null");
            return (Criteria) this;
        }

        public Criteria andErrorDescrEqualTo(String value) {
            addCriterion("error_descr =", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrNotEqualTo(String value) {
            addCriterion("error_descr <>", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrGreaterThan(String value) {
            addCriterion("error_descr >", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrGreaterThanOrEqualTo(String value) {
            addCriterion("error_descr >=", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrLessThan(String value) {
            addCriterion("error_descr <", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrLessThanOrEqualTo(String value) {
            addCriterion("error_descr <=", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrLike(String value) {
            addCriterion("error_descr like", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrNotLike(String value) {
            addCriterion("error_descr not like", value, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrIn(List<String> values) {
            addCriterion("error_descr in", values, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrNotIn(List<String> values) {
            addCriterion("error_descr not in", values, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrBetween(String value1, String value2) {
            addCriterion("error_descr between", value1, value2, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andErrorDescrNotBetween(String value1, String value2) {
            addCriterion("error_descr not between", value1, value2, "errorDescr");
            return (Criteria) this;
        }

        public Criteria andMainStatusIsNull() {
            addCriterion("main_status is null");
            return (Criteria) this;
        }

        public Criteria andMainStatusIsNotNull() {
            addCriterion("main_status is not null");
            return (Criteria) this;
        }

        public Criteria andMainStatusEqualTo(String value) {
            addCriterion("main_status =", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusNotEqualTo(String value) {
            addCriterion("main_status <>", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusGreaterThan(String value) {
            addCriterion("main_status >", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusGreaterThanOrEqualTo(String value) {
            addCriterion("main_status >=", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusLessThan(String value) {
            addCriterion("main_status <", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusLessThanOrEqualTo(String value) {
            addCriterion("main_status <=", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusLike(String value) {
            addCriterion("main_status like", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusNotLike(String value) {
            addCriterion("main_status not like", value, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusIn(List<String> values) {
            addCriterion("main_status in", values, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusNotIn(List<String> values) {
            addCriterion("main_status not in", values, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusBetween(String value1, String value2) {
            addCriterion("main_status between", value1, value2, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainStatusNotBetween(String value1, String value2) {
            addCriterion("main_status not between", value1, value2, "mainStatus");
            return (Criteria) this;
        }

        public Criteria andMainPeopleIsNull() {
            addCriterion("main_people is null");
            return (Criteria) this;
        }

        public Criteria andMainPeopleIsNotNull() {
            addCriterion("main_people is not null");
            return (Criteria) this;
        }

        public Criteria andMainPeopleEqualTo(String value) {
            addCriterion("main_people =", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleNotEqualTo(String value) {
            addCriterion("main_people <>", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleGreaterThan(String value) {
            addCriterion("main_people >", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("main_people >=", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleLessThan(String value) {
            addCriterion("main_people <", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleLessThanOrEqualTo(String value) {
            addCriterion("main_people <=", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleLike(String value) {
            addCriterion("main_people like", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleNotLike(String value) {
            addCriterion("main_people not like", value, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleIn(List<String> values) {
            addCriterion("main_people in", values, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleNotIn(List<String> values) {
            addCriterion("main_people not in", values, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleBetween(String value1, String value2) {
            addCriterion("main_people between", value1, value2, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPeopleNotBetween(String value1, String value2) {
            addCriterion("main_people not between", value1, value2, "mainPeople");
            return (Criteria) this;
        }

        public Criteria andMainPriceIsNull() {
            addCriterion("main_price is null");
            return (Criteria) this;
        }

        public Criteria andMainPriceIsNotNull() {
            addCriterion("main_price is not null");
            return (Criteria) this;
        }

        public Criteria andMainPriceEqualTo(Float value) {
            addCriterion("main_price =", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceNotEqualTo(Float value) {
            addCriterion("main_price <>", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceGreaterThan(Float value) {
            addCriterion("main_price >", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("main_price >=", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceLessThan(Float value) {
            addCriterion("main_price <", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceLessThanOrEqualTo(Float value) {
            addCriterion("main_price <=", value, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceIn(List<Float> values) {
            addCriterion("main_price in", values, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceNotIn(List<Float> values) {
            addCriterion("main_price not in", values, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceBetween(Float value1, Float value2) {
            addCriterion("main_price between", value1, value2, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainPriceNotBetween(Float value1, Float value2) {
            addCriterion("main_price not between", value1, value2, "mainPrice");
            return (Criteria) this;
        }

        public Criteria andMainDescrIsNull() {
            addCriterion("main_descr is null");
            return (Criteria) this;
        }

        public Criteria andMainDescrIsNotNull() {
            addCriterion("main_descr is not null");
            return (Criteria) this;
        }

        public Criteria andMainDescrEqualTo(String value) {
            addCriterion("main_descr =", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrNotEqualTo(String value) {
            addCriterion("main_descr <>", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrGreaterThan(String value) {
            addCriterion("main_descr >", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrGreaterThanOrEqualTo(String value) {
            addCriterion("main_descr >=", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrLessThan(String value) {
            addCriterion("main_descr <", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrLessThanOrEqualTo(String value) {
            addCriterion("main_descr <=", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrLike(String value) {
            addCriterion("main_descr like", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrNotLike(String value) {
            addCriterion("main_descr not like", value, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrIn(List<String> values) {
            addCriterion("main_descr in", values, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrNotIn(List<String> values) {
            addCriterion("main_descr not in", values, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrBetween(String value1, String value2) {
            addCriterion("main_descr between", value1, value2, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainDescrNotBetween(String value1, String value2) {
            addCriterion("main_descr not between", value1, value2, "mainDescr");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataIsNull() {
            addCriterion("main_finish_data is null");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataIsNotNull() {
            addCriterion("main_finish_data is not null");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataEqualTo(Date value) {
            addCriterion("main_finish_data =", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataNotEqualTo(Date value) {
            addCriterion("main_finish_data <>", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataGreaterThan(Date value) {
            addCriterion("main_finish_data >", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataGreaterThanOrEqualTo(Date value) {
            addCriterion("main_finish_data >=", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataLessThan(Date value) {
            addCriterion("main_finish_data <", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataLessThanOrEqualTo(Date value) {
            addCriterion("main_finish_data <=", value, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataIn(List<Date> values) {
            addCriterion("main_finish_data in", values, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataNotIn(List<Date> values) {
            addCriterion("main_finish_data not in", values, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataBetween(Date value1, Date value2) {
            addCriterion("main_finish_data between", value1, value2, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andMainFinishDataNotBetween(Date value1, Date value2) {
            addCriterion("main_finish_data not between", value1, value2, "mainFinishData");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIsNull() {
            addCriterion("verify_descr is null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIsNotNull() {
            addCriterion("verify_descr is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrEqualTo(String value) {
            addCriterion("verify_descr =", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotEqualTo(String value) {
            addCriterion("verify_descr <>", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrGreaterThan(String value) {
            addCriterion("verify_descr >", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrGreaterThanOrEqualTo(String value) {
            addCriterion("verify_descr >=", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLessThan(String value) {
            addCriterion("verify_descr <", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLessThanOrEqualTo(String value) {
            addCriterion("verify_descr <=", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLike(String value) {
            addCriterion("verify_descr like", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotLike(String value) {
            addCriterion("verify_descr not like", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIn(List<String> values) {
            addCriterion("verify_descr in", values, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotIn(List<String> values) {
            addCriterion("verify_descr not in", values, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrBetween(String value1, String value2) {
            addCriterion("verify_descr between", value1, value2, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotBetween(String value1, String value2) {
            addCriterion("verify_descr not between", value1, value2, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIsNull() {
            addCriterion("verift_passtime is null");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIsNotNull() {
            addCriterion("verift_passtime is not null");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeEqualTo(Date value) {
            addCriterion("verift_passtime =", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotEqualTo(Date value) {
            addCriterion("verift_passtime <>", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeGreaterThan(Date value) {
            addCriterion("verift_passtime >", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeGreaterThanOrEqualTo(Date value) {
            addCriterion("verift_passtime >=", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeLessThan(Date value) {
            addCriterion("verift_passtime <", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeLessThanOrEqualTo(Date value) {
            addCriterion("verift_passtime <=", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIn(List<Date> values) {
            addCriterion("verift_passtime in", values, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotIn(List<Date> values) {
            addCriterion("verift_passtime not in", values, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeBetween(Date value1, Date value2) {
            addCriterion("verift_passtime between", value1, value2, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotBetween(Date value1, Date value2) {
            addCriterion("verift_passtime not between", value1, value2, "veriftPasstime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}