package com.sjy.equipment_manager_system.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   保养计划表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_maintain_plan
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMaintainPlan implements Serializable {
    /**
     * Database Column Remarks:
     *   保养编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     * Database Column Remarks:
     *   保养类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.mtype
     *
     * @mbg.generated
     */
    private String mtype;

    /**
     * Database Column Remarks:
     *   保养开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    private Date maintainStartime;

    /**
     * Database Column Remarks:
     *   保养设备
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    private String maintainEquip;

    /**
     * Database Column Remarks:
     *   保养内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    private String maintainContent;

    /**
     * Database Column Remarks:
     *   保养人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.main_people
     *
     * @mbg.generated
     */
    private String mainPeople;

    /**
     * Database Column Remarks:
     *   保养描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.main_descr
     *
     * @mbg.generated
     */
    private String mainDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.mid
     *
     * @return the value of t_maintain_plan.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.mid
     *
     * @param mid the value for t_maintain_plan.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.mtype
     *
     * @return the value of t_maintain_plan.mtype
     *
     * @mbg.generated
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.mtype
     *
     * @param mtype the value for t_maintain_plan.mtype
     *
     * @mbg.generated
     */
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_startime
     *
     * @return the value of t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    public Date getMaintainStartime() {
        return maintainStartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_startime
     *
     * @param maintainStartime the value for t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    public void setMaintainStartime(Date maintainStartime) {
        this.maintainStartime = maintainStartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_equip
     *
     * @return the value of t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    public String getMaintainEquip() {
        return maintainEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_equip
     *
     * @param maintainEquip the value for t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    public void setMaintainEquip(String maintainEquip) {
        this.maintainEquip = maintainEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_content
     *
     * @return the value of t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    public String getMaintainContent() {
        return maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_content
     *
     * @param maintainContent the value for t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    public void setMaintainContent(String maintainContent) {
        this.maintainContent = maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.main_people
     *
     * @return the value of t_maintain_plan.main_people
     *
     * @mbg.generated
     */
    public String getMainPeople() {
        return mainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.main_people
     *
     * @param mainPeople the value for t_maintain_plan.main_people
     *
     * @mbg.generated
     */
    public void setMainPeople(String mainPeople) {
        this.mainPeople = mainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.main_descr
     *
     * @return the value of t_maintain_plan.main_descr
     *
     * @mbg.generated
     */
    public String getMainDescr() {
        return mainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.main_descr
     *
     * @param mainDescr the value for t_maintain_plan.main_descr
     *
     * @mbg.generated
     */
    public void setMainDescr(String mainDescr) {
        this.mainDescr = mainDescr;
    }
}