package com.sjy.equipment_manager_system.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMaintainSingleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public TMaintainSingleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeIsNull() {
            addCriterion("maintain_time is null");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeIsNotNull() {
            addCriterion("maintain_time is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeEqualTo(Date value) {
            addCriterion("maintain_time =", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeNotEqualTo(Date value) {
            addCriterion("maintain_time <>", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeGreaterThan(Date value) {
            addCriterion("maintain_time >", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("maintain_time >=", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeLessThan(Date value) {
            addCriterion("maintain_time <", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeLessThanOrEqualTo(Date value) {
            addCriterion("maintain_time <=", value, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeIn(List<Date> values) {
            addCriterion("maintain_time in", values, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeNotIn(List<Date> values) {
            addCriterion("maintain_time not in", values, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeBetween(Date value1, Date value2) {
            addCriterion("maintain_time between", value1, value2, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainTimeNotBetween(Date value1, Date value2) {
            addCriterion("maintain_time not between", value1, value2, "maintainTime");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberIsNull() {
            addCriterion("maintain_plan_number is null");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberIsNotNull() {
            addCriterion("maintain_plan_number is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberEqualTo(String value) {
            addCriterion("maintain_plan_number =", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberNotEqualTo(String value) {
            addCriterion("maintain_plan_number <>", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberGreaterThan(String value) {
            addCriterion("maintain_plan_number >", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberGreaterThanOrEqualTo(String value) {
            addCriterion("maintain_plan_number >=", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberLessThan(String value) {
            addCriterion("maintain_plan_number <", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberLessThanOrEqualTo(String value) {
            addCriterion("maintain_plan_number <=", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberLike(String value) {
            addCriterion("maintain_plan_number like", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberNotLike(String value) {
            addCriterion("maintain_plan_number not like", value, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberIn(List<String> values) {
            addCriterion("maintain_plan_number in", values, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberNotIn(List<String> values) {
            addCriterion("maintain_plan_number not in", values, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberBetween(String value1, String value2) {
            addCriterion("maintain_plan_number between", value1, value2, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainPlanNumberNotBetween(String value1, String value2) {
            addCriterion("maintain_plan_number not between", value1, value2, "maintainPlanNumber");
            return (Criteria) this;
        }

        public Criteria andMaintainContentIsNull() {
            addCriterion("maintain_content is null");
            return (Criteria) this;
        }

        public Criteria andMaintainContentIsNotNull() {
            addCriterion("maintain_content is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainContentEqualTo(String value) {
            addCriterion("maintain_content =", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentNotEqualTo(String value) {
            addCriterion("maintain_content <>", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentGreaterThan(String value) {
            addCriterion("maintain_content >", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentGreaterThanOrEqualTo(String value) {
            addCriterion("maintain_content >=", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentLessThan(String value) {
            addCriterion("maintain_content <", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentLessThanOrEqualTo(String value) {
            addCriterion("maintain_content <=", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentLike(String value) {
            addCriterion("maintain_content like", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentNotLike(String value) {
            addCriterion("maintain_content not like", value, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentIn(List<String> values) {
            addCriterion("maintain_content in", values, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentNotIn(List<String> values) {
            addCriterion("maintain_content not in", values, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentBetween(String value1, String value2) {
            addCriterion("maintain_content between", value1, value2, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainContentNotBetween(String value1, String value2) {
            addCriterion("maintain_content not between", value1, value2, "maintainContent");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusIsNull() {
            addCriterion("maintain_status is null");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusIsNotNull() {
            addCriterion("maintain_status is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusEqualTo(String value) {
            addCriterion("maintain_status =", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusNotEqualTo(String value) {
            addCriterion("maintain_status <>", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusGreaterThan(String value) {
            addCriterion("maintain_status >", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusGreaterThanOrEqualTo(String value) {
            addCriterion("maintain_status >=", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusLessThan(String value) {
            addCriterion("maintain_status <", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusLessThanOrEqualTo(String value) {
            addCriterion("maintain_status <=", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusLike(String value) {
            addCriterion("maintain_status like", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusNotLike(String value) {
            addCriterion("maintain_status not like", value, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusIn(List<String> values) {
            addCriterion("maintain_status in", values, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusNotIn(List<String> values) {
            addCriterion("maintain_status not in", values, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusBetween(String value1, String value2) {
            addCriterion("maintain_status between", value1, value2, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainStatusNotBetween(String value1, String value2) {
            addCriterion("maintain_status not between", value1, value2, "maintainStatus");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleIsNull() {
            addCriterion("maintain_people is null");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleIsNotNull() {
            addCriterion("maintain_people is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleEqualTo(String value) {
            addCriterion("maintain_people =", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleNotEqualTo(String value) {
            addCriterion("maintain_people <>", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleGreaterThan(String value) {
            addCriterion("maintain_people >", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("maintain_people >=", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleLessThan(String value) {
            addCriterion("maintain_people <", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleLessThanOrEqualTo(String value) {
            addCriterion("maintain_people <=", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleLike(String value) {
            addCriterion("maintain_people like", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleNotLike(String value) {
            addCriterion("maintain_people not like", value, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleIn(List<String> values) {
            addCriterion("maintain_people in", values, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleNotIn(List<String> values) {
            addCriterion("maintain_people not in", values, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleBetween(String value1, String value2) {
            addCriterion("maintain_people between", value1, value2, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPeopleNotBetween(String value1, String value2) {
            addCriterion("maintain_people not between", value1, value2, "maintainPeople");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceIsNull() {
            addCriterion("maintain_price is null");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceIsNotNull() {
            addCriterion("maintain_price is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceEqualTo(Float value) {
            addCriterion("maintain_price =", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceNotEqualTo(Float value) {
            addCriterion("maintain_price <>", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceGreaterThan(Float value) {
            addCriterion("maintain_price >", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("maintain_price >=", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceLessThan(Float value) {
            addCriterion("maintain_price <", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceLessThanOrEqualTo(Float value) {
            addCriterion("maintain_price <=", value, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceIn(List<Float> values) {
            addCriterion("maintain_price in", values, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceNotIn(List<Float> values) {
            addCriterion("maintain_price not in", values, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceBetween(Float value1, Float value2) {
            addCriterion("maintain_price between", value1, value2, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainPriceNotBetween(Float value1, Float value2) {
            addCriterion("maintain_price not between", value1, value2, "maintainPrice");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrIsNull() {
            addCriterion("maintain_descr is null");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrIsNotNull() {
            addCriterion("maintain_descr is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrEqualTo(String value) {
            addCriterion("maintain_descr =", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrNotEqualTo(String value) {
            addCriterion("maintain_descr <>", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrGreaterThan(String value) {
            addCriterion("maintain_descr >", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrGreaterThanOrEqualTo(String value) {
            addCriterion("maintain_descr >=", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrLessThan(String value) {
            addCriterion("maintain_descr <", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrLessThanOrEqualTo(String value) {
            addCriterion("maintain_descr <=", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrLike(String value) {
            addCriterion("maintain_descr like", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrNotLike(String value) {
            addCriterion("maintain_descr not like", value, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrIn(List<String> values) {
            addCriterion("maintain_descr in", values, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrNotIn(List<String> values) {
            addCriterion("maintain_descr not in", values, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrBetween(String value1, String value2) {
            addCriterion("maintain_descr between", value1, value2, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainDescrNotBetween(String value1, String value2) {
            addCriterion("maintain_descr not between", value1, value2, "maintainDescr");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeIsNull() {
            addCriterion("maintain_finish_time is null");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeIsNotNull() {
            addCriterion("maintain_finish_time is not null");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeEqualTo(Date value) {
            addCriterion("maintain_finish_time =", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeNotEqualTo(Date value) {
            addCriterion("maintain_finish_time <>", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeGreaterThan(Date value) {
            addCriterion("maintain_finish_time >", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("maintain_finish_time >=", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeLessThan(Date value) {
            addCriterion("maintain_finish_time <", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("maintain_finish_time <=", value, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeIn(List<Date> values) {
            addCriterion("maintain_finish_time in", values, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeNotIn(List<Date> values) {
            addCriterion("maintain_finish_time not in", values, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeBetween(Date value1, Date value2) {
            addCriterion("maintain_finish_time between", value1, value2, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andMaintainFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("maintain_finish_time not between", value1, value2, "maintainFinishTime");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIsNull() {
            addCriterion("verify_descr is null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIsNotNull() {
            addCriterion("verify_descr is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrEqualTo(String value) {
            addCriterion("verify_descr =", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotEqualTo(String value) {
            addCriterion("verify_descr <>", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrGreaterThan(String value) {
            addCriterion("verify_descr >", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrGreaterThanOrEqualTo(String value) {
            addCriterion("verify_descr >=", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLessThan(String value) {
            addCriterion("verify_descr <", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLessThanOrEqualTo(String value) {
            addCriterion("verify_descr <=", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrLike(String value) {
            addCriterion("verify_descr like", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotLike(String value) {
            addCriterion("verify_descr not like", value, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrIn(List<String> values) {
            addCriterion("verify_descr in", values, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotIn(List<String> values) {
            addCriterion("verify_descr not in", values, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrBetween(String value1, String value2) {
            addCriterion("verify_descr between", value1, value2, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVerifyDescrNotBetween(String value1, String value2) {
            addCriterion("verify_descr not between", value1, value2, "verifyDescr");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIsNull() {
            addCriterion("verift_passtime is null");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIsNotNull() {
            addCriterion("verift_passtime is not null");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeEqualTo(Date value) {
            addCriterion("verift_passtime =", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotEqualTo(Date value) {
            addCriterion("verift_passtime <>", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeGreaterThan(Date value) {
            addCriterion("verift_passtime >", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeGreaterThanOrEqualTo(Date value) {
            addCriterion("verift_passtime >=", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeLessThan(Date value) {
            addCriterion("verift_passtime <", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeLessThanOrEqualTo(Date value) {
            addCriterion("verift_passtime <=", value, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeIn(List<Date> values) {
            addCriterion("verift_passtime in", values, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotIn(List<Date> values) {
            addCriterion("verift_passtime not in", values, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeBetween(Date value1, Date value2) {
            addCriterion("verift_passtime between", value1, value2, "veriftPasstime");
            return (Criteria) this;
        }

        public Criteria andVeriftPasstimeNotBetween(Date value1, Date value2) {
            addCriterion("verift_passtime not between", value1, value2, "veriftPasstime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain_single
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}