package com.sjy.equipment_manager_system.dao;

import com.sjy.equipment_manager_system.entity.maintainDao;

public interface maintainDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insert(maintainDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insertSelective(maintainDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    maintainDao selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(maintainDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(maintainDao record);
}