package com.sjy.equipment_manager_system.dao;

import com.sjy.equipment_manager_system.entity.maintainPlanDap;

public interface maintainPlanDapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int insert(maintainPlanDap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int insertSelective(maintainPlanDap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    maintainPlanDap selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(maintainPlanDap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(maintainPlanDap record);
}