package com.sjy.equipment_manager_system.dao;

import com.sjy.equipment_manager_system.entity.maintainSingleDao;

public interface maintainSingleDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int insert(maintainSingleDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int insertSelective(maintainSingleDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    maintainSingleDao selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(maintainSingleDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(maintainSingleDao record);
}