package com.sjy.equipment_manager_system.dao;

import com.sjy.equipment_manager_system.entity.Maintain;
import com.sun.tools.javac.Main;

import java.util.List;

public interface MaintainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String maintainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insert(Maintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insertSelective(Maintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    Maintain selectByPrimaryKey(String maintainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Maintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Maintain record);

    /**
     * 自己写的mapper
     */

    List<Maintain> selectAll();
}