package com.sjy.equipment_manager_system.mbg.mapper;

import com.sjy.equipment_manager_system.mbg.model.RecommendSubject;
import com.sjy.equipment_manager_system.mbg.model.RecommendSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecommendSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    long countByExample(RecommendSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int deleteByExample(RecommendSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int insert(RecommendSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int insertSelective(RecommendSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    List<RecommendSubject> selectByExample(RecommendSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    RecommendSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RecommendSubject record, @Param("example") RecommendSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RecommendSubject record, @Param("example") RecommendSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecommendSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecommendSubject record);
}