package com.sjy.equipment_manager_system.mbg.mapper;

import com.sjy.equipment_manager_system.mbg.model.TMaintain;
import com.sjy.equipment_manager_system.mbg.model.TMaintainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMaintainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    long countByExample(TMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int deleteByExample(TMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insert(TMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int insertSelective(TMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    List<TMaintain> selectByExample(TMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    TMaintain selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMaintain record, @Param("example") TMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMaintain record, @Param("example") TMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMaintain record);
}