package com.sjy.equipment_manager_system.mbg.mapper;

import com.sjy.equipment_manager_system.mbg.model.TMaintainSingle;
import com.sjy.equipment_manager_system.mbg.model.TMaintainSingleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMaintainSingleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    long countByExample(TMaintainSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int deleteByExample(TMaintainSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int insert(TMaintainSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int insertSelective(TMaintainSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    List<TMaintainSingle> selectByExample(TMaintainSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    TMaintainSingle selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMaintainSingle record, @Param("example") TMaintainSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMaintainSingle record, @Param("example") TMaintainSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMaintainSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMaintainSingle record);
}