package com.sjy.equipment_manager_system.mbg.mapper;

import com.sjy.equipment_manager_system.mbg.model.TMaintainPlan;
import com.sjy.equipment_manager_system.mbg.model.TMaintainPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMaintainPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    long countByExample(TMaintainPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int deleteByExample(TMaintainPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int insert(TMaintainPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int insertSelective(TMaintainPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    List<TMaintainPlan> selectByExample(TMaintainPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    TMaintainPlan selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMaintainPlan record, @Param("example") TMaintainPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMaintainPlan record, @Param("example") TMaintainPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMaintainPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMaintainPlan record);
}