package com.sjy.equipment_manager_system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   维修管理表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_maintain
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class maintainDao implements Serializable {
    /**
     * Database Column Remarks:
     *   维修单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     * Database Column Remarks:
     *   维修填报时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.msubmit_time
     *
     * @mbg.generated
     */
    private Date msubmitTime;

    /**
     * Database Column Remarks:
     *   维修上报人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.msubmit_people
     *
     * @mbg.generated
     */
    private String msubmitPeople;

    /**
     * Database Column Remarks:
     *   故障设备
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.error_equip
     *
     * @mbg.generated
     */
    private String errorEquip;

    /**
     * Database Column Remarks:
     *   故障描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.error_descr
     *
     * @mbg.generated
     */
    private String errorDescr;

    /**
     * Database Column Remarks:
     *   维修状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.main_status
     *
     * @mbg.generated
     */
    private String mainStatus;

    /**
     * Database Column Remarks:
     *   维修人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.main_people
     *
     * @mbg.generated
     */
    private String mainPeople;

    /**
     * Database Column Remarks:
     *   维修费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.main_price
     *
     * @mbg.generated
     */
    private Float mainPrice;

    /**
     * Database Column Remarks:
     *   维修描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.main_descr
     *
     * @mbg.generated
     */
    private String mainDescr;

    /**
     * Database Column Remarks:
     *   验证描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.verify_descr
     *
     * @mbg.generated
     */
    private String verifyDescr;

    /**
     * Database Column Remarks:
     *   验证通过时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.verift_passtime
     *
     * @mbg.generated
     */
    private Date veriftPasstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.main_finish_date
     *
     * @mbg.generated
     */
    private Date mainFinishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.mid
     *
     * @return the value of t_maintain.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.mid
     *
     * @param mid the value for t_maintain.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.msubmit_time
     *
     * @return the value of t_maintain.msubmit_time
     *
     * @mbg.generated
     */
    public Date getMsubmitTime() {
        return msubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.msubmit_time
     *
     * @param msubmitTime the value for t_maintain.msubmit_time
     *
     * @mbg.generated
     */
    public void setMsubmitTime(Date msubmitTime) {
        this.msubmitTime = msubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.msubmit_people
     *
     * @return the value of t_maintain.msubmit_people
     *
     * @mbg.generated
     */
    public String getMsubmitPeople() {
        return msubmitPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.msubmit_people
     *
     * @param msubmitPeople the value for t_maintain.msubmit_people
     *
     * @mbg.generated
     */
    public void setMsubmitPeople(String msubmitPeople) {
        this.msubmitPeople = msubmitPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.error_equip
     *
     * @return the value of t_maintain.error_equip
     *
     * @mbg.generated
     */
    public String getErrorEquip() {
        return errorEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.error_equip
     *
     * @param errorEquip the value for t_maintain.error_equip
     *
     * @mbg.generated
     */
    public void setErrorEquip(String errorEquip) {
        this.errorEquip = errorEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.error_descr
     *
     * @return the value of t_maintain.error_descr
     *
     * @mbg.generated
     */
    public String getErrorDescr() {
        return errorDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.error_descr
     *
     * @param errorDescr the value for t_maintain.error_descr
     *
     * @mbg.generated
     */
    public void setErrorDescr(String errorDescr) {
        this.errorDescr = errorDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.main_status
     *
     * @return the value of t_maintain.main_status
     *
     * @mbg.generated
     */
    public String getMainStatus() {
        return mainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.main_status
     *
     * @param mainStatus the value for t_maintain.main_status
     *
     * @mbg.generated
     */
    public void setMainStatus(String mainStatus) {
        this.mainStatus = mainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.main_people
     *
     * @return the value of t_maintain.main_people
     *
     * @mbg.generated
     */
    public String getMainPeople() {
        return mainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.main_people
     *
     * @param mainPeople the value for t_maintain.main_people
     *
     * @mbg.generated
     */
    public void setMainPeople(String mainPeople) {
        this.mainPeople = mainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.main_price
     *
     * @return the value of t_maintain.main_price
     *
     * @mbg.generated
     */
    public Float getMainPrice() {
        return mainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.main_price
     *
     * @param mainPrice the value for t_maintain.main_price
     *
     * @mbg.generated
     */
    public void setMainPrice(Float mainPrice) {
        this.mainPrice = mainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.main_descr
     *
     * @return the value of t_maintain.main_descr
     *
     * @mbg.generated
     */
    public String getMainDescr() {
        return mainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.main_descr
     *
     * @param mainDescr the value for t_maintain.main_descr
     *
     * @mbg.generated
     */
    public void setMainDescr(String mainDescr) {
        this.mainDescr = mainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.verify_descr
     *
     * @return the value of t_maintain.verify_descr
     *
     * @mbg.generated
     */
    public String getVerifyDescr() {
        return verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.verify_descr
     *
     * @param verifyDescr the value for t_maintain.verify_descr
     *
     * @mbg.generated
     */
    public void setVerifyDescr(String verifyDescr) {
        this.verifyDescr = verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.verift_passtime
     *
     * @return the value of t_maintain.verift_passtime
     *
     * @mbg.generated
     */
    public Date getVeriftPasstime() {
        return veriftPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.verift_passtime
     *
     * @param veriftPasstime the value for t_maintain.verift_passtime
     *
     * @mbg.generated
     */
    public void setVeriftPasstime(Date veriftPasstime) {
        this.veriftPasstime = veriftPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.main_finish_date
     *
     * @return the value of t_maintain.main_finish_date
     *
     * @mbg.generated
     */
    public Date getMainFinishDate() {
        return mainFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.main_finish_date
     *
     * @param mainFinishDate the value for t_maintain.main_finish_date
     *
     * @mbg.generated
     */
    public void setMainFinishDate(Date mainFinishDate) {
        this.mainFinishDate = mainFinishDate;
    }
}