package com.sjy.equipment_manager_system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   保养单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_maintain_single
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class maintainSingleDao implements Serializable {
    /**
     * Database Column Remarks:
     *   保养单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     * Database Column Remarks:
     *   保养时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_time
     *
     * @mbg.generated
     */
    private Date maintainTime;

    /**
     * Database Column Remarks:
     *   保养计划编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_plan_number
     *
     * @mbg.generated
     */
    private String maintainPlanNumber;

    /**
     * Database Column Remarks:
     *   保养内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_content
     *
     * @mbg.generated
     */
    private String maintainContent;

    /**
     * Database Column Remarks:
     *   保养状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_status
     *
     * @mbg.generated
     */
    private String maintainStatus;

    /**
     * Database Column Remarks:
     *   保养人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_people
     *
     * @mbg.generated
     */
    private String maintainPeople;

    /**
     * Database Column Remarks:
     *   保养费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_price
     *
     * @mbg.generated
     */
    private Float maintainPrice;

    /**
     * Database Column Remarks:
     *   保养描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_descr
     *
     * @mbg.generated
     */
    private String maintainDescr;

    /**
     * Database Column Remarks:
     *   保养完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.maintain_finish_time
     *
     * @mbg.generated
     */
    private Date maintainFinishTime;

    /**
     * Database Column Remarks:
     *   验证描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.verify_descr
     *
     * @mbg.generated
     */
    private String verifyDescr;

    /**
     * Database Column Remarks:
     *   验证通过时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_single.verift_passtime
     *
     * @mbg.generated
     */
    private Date veriftPasstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_single
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.mid
     *
     * @return the value of t_maintain_single.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.mid
     *
     * @param mid the value for t_maintain_single.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_time
     *
     * @return the value of t_maintain_single.maintain_time
     *
     * @mbg.generated
     */
    public Date getMaintainTime() {
        return maintainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_time
     *
     * @param maintainTime the value for t_maintain_single.maintain_time
     *
     * @mbg.generated
     */
    public void setMaintainTime(Date maintainTime) {
        this.maintainTime = maintainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_plan_number
     *
     * @return the value of t_maintain_single.maintain_plan_number
     *
     * @mbg.generated
     */
    public String getMaintainPlanNumber() {
        return maintainPlanNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_plan_number
     *
     * @param maintainPlanNumber the value for t_maintain_single.maintain_plan_number
     *
     * @mbg.generated
     */
    public void setMaintainPlanNumber(String maintainPlanNumber) {
        this.maintainPlanNumber = maintainPlanNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_content
     *
     * @return the value of t_maintain_single.maintain_content
     *
     * @mbg.generated
     */
    public String getMaintainContent() {
        return maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_content
     *
     * @param maintainContent the value for t_maintain_single.maintain_content
     *
     * @mbg.generated
     */
    public void setMaintainContent(String maintainContent) {
        this.maintainContent = maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_status
     *
     * @return the value of t_maintain_single.maintain_status
     *
     * @mbg.generated
     */
    public String getMaintainStatus() {
        return maintainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_status
     *
     * @param maintainStatus the value for t_maintain_single.maintain_status
     *
     * @mbg.generated
     */
    public void setMaintainStatus(String maintainStatus) {
        this.maintainStatus = maintainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_people
     *
     * @return the value of t_maintain_single.maintain_people
     *
     * @mbg.generated
     */
    public String getMaintainPeople() {
        return maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_people
     *
     * @param maintainPeople the value for t_maintain_single.maintain_people
     *
     * @mbg.generated
     */
    public void setMaintainPeople(String maintainPeople) {
        this.maintainPeople = maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_price
     *
     * @return the value of t_maintain_single.maintain_price
     *
     * @mbg.generated
     */
    public Float getMaintainPrice() {
        return maintainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_price
     *
     * @param maintainPrice the value for t_maintain_single.maintain_price
     *
     * @mbg.generated
     */
    public void setMaintainPrice(Float maintainPrice) {
        this.maintainPrice = maintainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_descr
     *
     * @return the value of t_maintain_single.maintain_descr
     *
     * @mbg.generated
     */
    public String getMaintainDescr() {
        return maintainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_descr
     *
     * @param maintainDescr the value for t_maintain_single.maintain_descr
     *
     * @mbg.generated
     */
    public void setMaintainDescr(String maintainDescr) {
        this.maintainDescr = maintainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.maintain_finish_time
     *
     * @return the value of t_maintain_single.maintain_finish_time
     *
     * @mbg.generated
     */
    public Date getMaintainFinishTime() {
        return maintainFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.maintain_finish_time
     *
     * @param maintainFinishTime the value for t_maintain_single.maintain_finish_time
     *
     * @mbg.generated
     */
    public void setMaintainFinishTime(Date maintainFinishTime) {
        this.maintainFinishTime = maintainFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.verify_descr
     *
     * @return the value of t_maintain_single.verify_descr
     *
     * @mbg.generated
     */
    public String getVerifyDescr() {
        return verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.verify_descr
     *
     * @param verifyDescr the value for t_maintain_single.verify_descr
     *
     * @mbg.generated
     */
    public void setVerifyDescr(String verifyDescr) {
        this.verifyDescr = verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_single.verift_passtime
     *
     * @return the value of t_maintain_single.verift_passtime
     *
     * @mbg.generated
     */
    public Date getVeriftPasstime() {
        return veriftPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_single.verift_passtime
     *
     * @param veriftPasstime the value for t_maintain_single.verift_passtime
     *
     * @mbg.generated
     */
    public void setVeriftPasstime(Date veriftPasstime) {
        this.veriftPasstime = veriftPasstime;
    }
}