package com.sjy.equipment_manager_system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_maintain
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Maintain implements Serializable {
    /**
     * Database Column Remarks:
     *   保养单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_id
     *
     * @mbg.generated
     */
    private String maintainId;

    /**
     * Database Column Remarks:
     *   保养时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_time
     *
     * @mbg.generated
     */
    private Date maintainTime;

    /**
     * Database Column Remarks:
     *   保养计划编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_plan_id
     *
     * @mbg.generated
     */
    private String maintainPlanId;

    /**
     * Database Column Remarks:
     *   保养内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_content
     *
     * @mbg.generated
     */
    private String maintainContent;

    /**
     * Database Column Remarks:
     *   保养状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_status
     *
     * @mbg.generated
     */
    private String maintainStatus;

    /**
     * Database Column Remarks:
     *   保养人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_people
     *
     * @mbg.generated
     */
    private String maintainPeople;

    /**
     * Database Column Remarks:
     *   保养费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_price
     *
     * @mbg.generated
     */
    private Float maintainPrice;

    /**
     * Database Column Remarks:
     *   保养描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_descr
     *
     * @mbg.generated
     */
    private String maintainDescr;

    /**
     * Database Column Remarks:
     *   保养完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.maintain_finish_date
     *
     * @mbg.generated
     */
    private Date maintainFinishDate;

    /**
     * Database Column Remarks:
     *   验证描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.verify_descr
     *
     * @mbg.generated
     */
    private String verifyDescr;

    /**
     * Database Column Remarks:
     *   验证通过时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain.verify_passtime
     *
     * @mbg.generated
     */
    private Date verifyPasstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_id
     *
     * @return the value of t_maintain.maintain_id
     *
     * @mbg.generated
     */
    public String getMaintainId() {
        return maintainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_id
     *
     * @param maintainId the value for t_maintain.maintain_id
     *
     * @mbg.generated
     */
    public void setMaintainId(String maintainId) {
        this.maintainId = maintainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_time
     *
     * @return the value of t_maintain.maintain_time
     *
     * @mbg.generated
     */
    public Date getMaintainTime() {
        return maintainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_time
     *
     * @param maintainTime the value for t_maintain.maintain_time
     *
     * @mbg.generated
     */
    public void setMaintainTime(Date maintainTime) {
        this.maintainTime = maintainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_plan_id
     *
     * @return the value of t_maintain.maintain_plan_id
     *
     * @mbg.generated
     */
    public String getMaintainPlanId() {
        return maintainPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_plan_id
     *
     * @param maintainPlanId the value for t_maintain.maintain_plan_id
     *
     * @mbg.generated
     */
    public void setMaintainPlanId(String maintainPlanId) {
        this.maintainPlanId = maintainPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_content
     *
     * @return the value of t_maintain.maintain_content
     *
     * @mbg.generated
     */
    public String getMaintainContent() {
        return maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_content
     *
     * @param maintainContent the value for t_maintain.maintain_content
     *
     * @mbg.generated
     */
    public void setMaintainContent(String maintainContent) {
        this.maintainContent = maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_status
     *
     * @return the value of t_maintain.maintain_status
     *
     * @mbg.generated
     */
    public String getMaintainStatus() {
        return maintainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_status
     *
     * @param maintainStatus the value for t_maintain.maintain_status
     *
     * @mbg.generated
     */
    public void setMaintainStatus(String maintainStatus) {
        this.maintainStatus = maintainStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_people
     *
     * @return the value of t_maintain.maintain_people
     *
     * @mbg.generated
     */
    public String getMaintainPeople() {
        return maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_people
     *
     * @param maintainPeople the value for t_maintain.maintain_people
     *
     * @mbg.generated
     */
    public void setMaintainPeople(String maintainPeople) {
        this.maintainPeople = maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_price
     *
     * @return the value of t_maintain.maintain_price
     *
     * @mbg.generated
     */
    public Float getMaintainPrice() {
        return maintainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_price
     *
     * @param maintainPrice the value for t_maintain.maintain_price
     *
     * @mbg.generated
     */
    public void setMaintainPrice(Float maintainPrice) {
        this.maintainPrice = maintainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_descr
     *
     * @return the value of t_maintain.maintain_descr
     *
     * @mbg.generated
     */
    public String getMaintainDescr() {
        return maintainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_descr
     *
     * @param maintainDescr the value for t_maintain.maintain_descr
     *
     * @mbg.generated
     */
    public void setMaintainDescr(String maintainDescr) {
        this.maintainDescr = maintainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.maintain_finish_date
     *
     * @return the value of t_maintain.maintain_finish_date
     *
     * @mbg.generated
     */
    public Date getMaintainFinishDate() {
        return maintainFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.maintain_finish_date
     *
     * @param maintainFinishDate the value for t_maintain.maintain_finish_date
     *
     * @mbg.generated
     */
    public void setMaintainFinishDate(Date maintainFinishDate) {
        this.maintainFinishDate = maintainFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.verify_descr
     *
     * @return the value of t_maintain.verify_descr
     *
     * @mbg.generated
     */
    public String getVerifyDescr() {
        return verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.verify_descr
     *
     * @param verifyDescr the value for t_maintain.verify_descr
     *
     * @mbg.generated
     */
    public void setVerifyDescr(String verifyDescr) {
        this.verifyDescr = verifyDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain.verify_passtime
     *
     * @return the value of t_maintain.verify_passtime
     *
     * @mbg.generated
     */
    public Date getVerifyPasstime() {
        return verifyPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain.verify_passtime
     *
     * @param verifyPasstime the value for t_maintain.verify_passtime
     *
     * @mbg.generated
     */
    public void setVerifyPasstime(Date verifyPasstime) {
        this.verifyPasstime = verifyPasstime;
    }
}