package com.sjy.equipment_manager_system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_maintain_plan
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MaintainPlan implements Serializable {
    /**
     * Database Column Remarks:
     *   保养编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_plan_id
     *
     * @mbg.generated
     */
    private String maintainPlanId;

    /**
     * Database Column Remarks:
     *   保养类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_type
     *
     * @mbg.generated
     */
    private String maintainType;

    /**
     * Database Column Remarks:
     *   保养开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    private Date maintainStartime;

    /**
     * Database Column Remarks:
     *   保养设备
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    private String maintainEquip;

    /**
     * Database Column Remarks:
     *   保养内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    private String maintainContent;

    /**
     * Database Column Remarks:
     *   保养人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_people
     *
     * @mbg.generated
     */
    private String maintainPeople;

    /**
     * Database Column Remarks:
     *   保养描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maintain_plan.maintain_descr
     *
     * @mbg.generated
     */
    private String maintainDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maintain_plan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_plan_id
     *
     * @return the value of t_maintain_plan.maintain_plan_id
     *
     * @mbg.generated
     */
    public String getMaintainPlanId() {
        return maintainPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_plan_id
     *
     * @param maintainPlanId the value for t_maintain_plan.maintain_plan_id
     *
     * @mbg.generated
     */
    public void setMaintainPlanId(String maintainPlanId) {
        this.maintainPlanId = maintainPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_type
     *
     * @return the value of t_maintain_plan.maintain_type
     *
     * @mbg.generated
     */
    public String getMaintainType() {
        return maintainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_type
     *
     * @param maintainType the value for t_maintain_plan.maintain_type
     *
     * @mbg.generated
     */
    public void setMaintainType(String maintainType) {
        this.maintainType = maintainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_startime
     *
     * @return the value of t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    public Date getMaintainStartime() {
        return maintainStartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_startime
     *
     * @param maintainStartime the value for t_maintain_plan.maintain_startime
     *
     * @mbg.generated
     */
    public void setMaintainStartime(Date maintainStartime) {
        this.maintainStartime = maintainStartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_equip
     *
     * @return the value of t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    public String getMaintainEquip() {
        return maintainEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_equip
     *
     * @param maintainEquip the value for t_maintain_plan.maintain_equip
     *
     * @mbg.generated
     */
    public void setMaintainEquip(String maintainEquip) {
        this.maintainEquip = maintainEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_content
     *
     * @return the value of t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    public String getMaintainContent() {
        return maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_content
     *
     * @param maintainContent the value for t_maintain_plan.maintain_content
     *
     * @mbg.generated
     */
    public void setMaintainContent(String maintainContent) {
        this.maintainContent = maintainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_people
     *
     * @return the value of t_maintain_plan.maintain_people
     *
     * @mbg.generated
     */
    public String getMaintainPeople() {
        return maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_people
     *
     * @param maintainPeople the value for t_maintain_plan.maintain_people
     *
     * @mbg.generated
     */
    public void setMaintainPeople(String maintainPeople) {
        this.maintainPeople = maintainPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maintain_plan.maintain_descr
     *
     * @return the value of t_maintain_plan.maintain_descr
     *
     * @mbg.generated
     */
    public String getMaintainDescr() {
        return maintainDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maintain_plan.maintain_descr
     *
     * @param maintainDescr the value for t_maintain_plan.maintain_descr
     *
     * @mbg.generated
     */
    public void setMaintainDescr(String maintainDescr) {
        this.maintainDescr = maintainDescr;
    }
}