package com.sjy.equipment_manager_system.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_staff
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Staff implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     * Database Column Remarks:
     *   工作人员用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff.staff_name
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     * Database Column Remarks:
     *   工作人员密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff.staff_pwd
     *
     * @mbg.generated
     */
    private String staffPwd;

    /**
     * Database Column Remarks:
     *   工作人员工作职位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff.staff_job
     *
     * @mbg.generated
     */
    private String staffJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_staff
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff.staff_id
     *
     * @return the value of t_staff.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff.staff_id
     *
     * @param staffId the value for t_staff.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff.staff_name
     *
     * @return the value of t_staff.staff_name
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff.staff_name
     *
     * @param staffName the value for t_staff.staff_name
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff.staff_pwd
     *
     * @return the value of t_staff.staff_pwd
     *
     * @mbg.generated
     */
    public String getStaffPwd() {
        return staffPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff.staff_pwd
     *
     * @param staffPwd the value for t_staff.staff_pwd
     *
     * @mbg.generated
     */
    public void setStaffPwd(String staffPwd) {
        this.staffPwd = staffPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff.staff_job
     *
     * @return the value of t_staff.staff_job
     *
     * @mbg.generated
     */
    public String getStaffJob() {
        return staffJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff.staff_job
     *
     * @param staffJob the value for t_staff.staff_job
     *
     * @mbg.generated
     */
    public void setStaffJob(String staffJob) {
        this.staffJob = staffJob;
    }
}