package com.sjy.insurance.dao;

import com.sjy.insurance.entity.Carousel;

import java.util.List;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    Carousel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Carousel record);

    int delAll();

    int insertBySub();

    List<Carousel> queryAll();
}