package com.sjy.insurance.dao;

import com.sjy.insurance.entity.Claim;

public interface ClaimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    int insert(Claim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    int insertSelective(Claim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    Claim selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Claim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Claim record);
}