package com.sjy.insurance.dao;

import com.sjy.insurance.entity.CustomerUser;

import java.util.List;

public interface CustomerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int insert(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int insertSelective(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    CustomerUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerUser record);

    /**
     * coder by sonder
     */

    /**
     * 请求所有的顾客
     * @return
     */
    List<CustomerUser> queryAll();

    int login(String loginName, String loginPassword);
}