package com.sjy.insurance.dao;

import com.sjy.insurance.entity.CustomerUser;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface CustomerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int insert(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int insertSelective(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    CustomerUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerUser record);

    /**
     * coder by sonder
     */

    List<CustomerUser> queryAll();

    int login(String loginName, String loginPassword);

    @Update("update t_insurance_mall_user set login_password=#{loginPassword}  where login_name=#{loginName} ")
    int updateLoginPassword(@Param("loginPassword") String loginPasword, @Param("loginName") String loginName);
}