package com.sjy.insurance.dao;

import com.sjy.insurance.bo.GoodsAbbre;
import com.sjy.insurance.entity.Goods;
import com.sjy.insurance.entity.GuaranteeTmp;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    Goods selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods record);

    /**
     * conder by sonder
     */

    List<Goods> queryAllUpLimit();

//    @Select("select * from t_insurance_mall_goods_info where create_user = #{loginName}")
    List<Goods> queryAllByCreateUser(String loginName);

    List<GoodsAbbre> queryAllAbbreByCreateUser(String loginName);


    @Update("update t_insurance_mall_goods_info set goods_sell_status = #{status} where goods_name = #{goodName}")
    int updateStatusByGoodName(int status, String goodName);

//    @Select("select * from t_insurance_mall_goods_info where goods_name=#{goodName}")
    Goods queryGoodsDetail(String goodName);

    int updateTotal(GuaranteeTmp guaranteeTmp);

    List<Goods> selectAllByGoodsCategoryId(int type);
}