package com.sjy.insurance.dao;

import com.sjy.insurance.entity.GuaranteeSlip;

public interface GuaranteeSlipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insert(GuaranteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insertSelective(GuaranteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    GuaranteeSlip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GuaranteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GuaranteeSlip record);
}