package com.sjy.insurance.dao;

import com.sjy.insurance.entity.GuarenteeSlip;

public interface GuarenteeSlipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insert(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insertSelective(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    GuarenteeSlip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GuarenteeSlip record);
}