package com.sjy.insurance.dao;

import com.sjy.insurance.entity.GuaranteeTmp;
import com.sjy.insurance.entity.GuarenteeSlip;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface GuarenteeSlipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insert(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int insertSelective(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    List<GuarenteeSlip> selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GuarenteeSlip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_guarantee_slip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GuarenteeSlip record);

    List<GuarenteeSlip> queryAll();

//    @Select("select * from t_insurance_guarantee_slip where buyer = #{loginName}")
    List<GuarenteeSlip> queryAllByOwner(String loginName);

    List<GuaranteeTmp> queryProductCount();

    List<GuarenteeSlip> queryAllByCompany(String company, String userName);
}