package com.sjy.insurance.dao;

import com.sjy.insurance.entity.Insurer;

import java.util.List;

public interface InsurerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    int insert(Insurer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    int insertSelective(Insurer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    Insurer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Insurer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Insurer record);

    List<Insurer> selectAllInsurer(String belongAcc);
}