package com.sjy.insurance.dao;

import com.github.pagehelper.Page;
import com.sjy.insurance.entity.Goods;
import com.sjy.insurance.entity.TopLine;

import java.util.List;

public interface TopLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int insert(TopLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int insertSelective(TopLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    TopLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TopLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TopLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TopLine record);

    /**
     * select by sonder
     */

    List<TopLine> selectAllLimit();

    List<TopLine> findAll();

}