package com.sjy.insurance.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   保险商城管理员
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_mall_admin_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AdminUser implements Serializable {
    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.admin_user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("管理员id")
    private Long adminUserId;

    /**
     * Database Column Remarks:
     *   管理员登陆名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.login_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("管理员登陆名称")
    private String loginName;

    /**
     * Database Column Remarks:
     *   管理员登陆密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.login_password
     *
     * @mbg.generated
     */
    @ApiModelProperty("管理员登陆密码")
    private String loginPassword;

    @ApiModelProperty("管理员注册手机号")
    private String loginMobile;

    /**
     * Database Column Remarks:
     *   管理员显示昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.nick_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("管理员显示昵称")
    private String nickName;

    /**
     * Database Column Remarks:
     *   是否锁定 0未锁定 1已锁定无法登陆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.locked
     *
     * @mbg.generated
     */
    @ApiModelProperty("是否锁定 0未锁定 1已锁定无法登陆")
    private Byte locked;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_admin_user.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty("注册时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_mall_admin_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.admin_user_id
     *
     * @return the value of t_insurance_mall_admin_user.admin_user_id
     *
     * @mbg.generated
     */



    public Long getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.admin_user_id
     *
     * @param adminUserId the value for t_insurance_mall_admin_user.admin_user_id
     *
     * @mbg.generated
     */
    public void setAdminUserId(Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.login_name
     *
     * @return the value of t_insurance_mall_admin_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.login_name
     *
     * @param loginName the value for t_insurance_mall_admin_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.login_password
     *
     * @return the value of t_insurance_mall_admin_user.login_password
     *
     * @mbg.generated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.login_password
     *
     * @param loginPassword the value for t_insurance_mall_admin_user.login_password
     *
     * @mbg.generated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.nick_name
     *
     * @return the value of t_insurance_mall_admin_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.nick_name
     *
     * @param nickName the value for t_insurance_mall_admin_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.locked
     *
     * @return the value of t_insurance_mall_admin_user.locked
     *
     * @mbg.generated
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.locked
     *
     * @param locked the value for t_insurance_mall_admin_user.locked
     *
     * @mbg.generated
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_admin_user.create_time
     *
     * @return the value of t_insurance_mall_admin_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_admin_user.create_time
     *
     * @param createTime the value for t_insurance_mall_admin_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getLoginMobile() {
        return loginMobile;
    }

    public void setLoginMobile(String loginMobile) {
        this.loginMobile = loginMobile;
    }
}