package com.sjy.insurance.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_carousel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Carousel implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_carousel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   保险名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_carousel.insurance_name
     *
     * @mbg.generated
     */
    private String insuranceName;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_carousel.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_carousel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_carousel.id
     *
     * @return the value of t_insurance_carousel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_carousel.id
     *
     * @param id the value for t_insurance_carousel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_carousel.insurance_name
     *
     * @return the value of t_insurance_carousel.insurance_name
     *
     * @mbg.generated
     */
    public String getInsuranceName() {
        return insuranceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_carousel.insurance_name
     *
     * @param insuranceName the value for t_insurance_carousel.insurance_name
     *
     * @mbg.generated
     */
    public void setInsuranceName(String insuranceName) {
        this.insuranceName = insuranceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_carousel.imgUrl
     *
     * @return the value of t_insurance_carousel.imgUrl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_carousel.imgUrl
     *
     * @param imgurl the value for t_insurance_carousel.imgUrl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }
}