package com.sjy.insurance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_claim
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Claim implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   保单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.guarantee_no
     *
     * @mbg.generated
     */
    private String guaranteeNo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   事故日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.event_time
     *
     * @mbg.generated
     */
    private Date eventTime;

    /**
     * Database Column Remarks:
     *   事故地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.location_accident
     *
     * @mbg.generated
     */
    private String locationAccident;

    /**
     * Database Column Remarks:
     *   事故描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.accident_desc
     *
     * @mbg.generated
     */
    private String accidentDesc;

    /**
     * Database Column Remarks:
     *   报案状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   报案人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.submitter
     *
     * @mbg.generated
     */
    private String submitter;

    /**
     * Database Column Remarks:
     *   处理人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_claim.resolver
     *
     * @mbg.generated
     */
    private String resolver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_claim
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.id
     *
     * @return the value of t_insurance_claim.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.id
     *
     * @param id the value for t_insurance_claim.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.guarantee_no
     *
     * @return the value of t_insurance_claim.guarantee_no
     *
     * @mbg.generated
     */
    public String getGuaranteeNo() {
        return guaranteeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.guarantee_no
     *
     * @param guaranteeNo the value for t_insurance_claim.guarantee_no
     *
     * @mbg.generated
     */
    public void setGuaranteeNo(String guaranteeNo) {
        this.guaranteeNo = guaranteeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.create_time
     *
     * @return the value of t_insurance_claim.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.create_time
     *
     * @param createTime the value for t_insurance_claim.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.event_time
     *
     * @return the value of t_insurance_claim.event_time
     *
     * @mbg.generated
     */
    public Date getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.event_time
     *
     * @param eventTime the value for t_insurance_claim.event_time
     *
     * @mbg.generated
     */
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.location_accident
     *
     * @return the value of t_insurance_claim.location_accident
     *
     * @mbg.generated
     */
    public String getLocationAccident() {
        return locationAccident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.location_accident
     *
     * @param locationAccident the value for t_insurance_claim.location_accident
     *
     * @mbg.generated
     */
    public void setLocationAccident(String locationAccident) {
        this.locationAccident = locationAccident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.accident_desc
     *
     * @return the value of t_insurance_claim.accident_desc
     *
     * @mbg.generated
     */
    public String getAccidentDesc() {
        return accidentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.accident_desc
     *
     * @param accidentDesc the value for t_insurance_claim.accident_desc
     *
     * @mbg.generated
     */
    public void setAccidentDesc(String accidentDesc) {
        this.accidentDesc = accidentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.status
     *
     * @return the value of t_insurance_claim.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.status
     *
     * @param status the value for t_insurance_claim.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.submitter
     *
     * @return the value of t_insurance_claim.submitter
     *
     * @mbg.generated
     */
    public String getSubmitter() {
        return submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.submitter
     *
     * @param submitter the value for t_insurance_claim.submitter
     *
     * @mbg.generated
     */
    public void setSubmitter(String submitter) {
        this.submitter = submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_claim.resolver
     *
     * @return the value of t_insurance_claim.resolver
     *
     * @mbg.generated
     */
    public String getResolver() {
        return resolver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_claim.resolver
     *
     * @param resolver the value for t_insurance_claim.resolver
     *
     * @mbg.generated
     */
    public void setResolver(String resolver) {
        this.resolver = resolver;
    }
}