package com.sjy.insurance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   会员用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_mall_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CustomerUser implements Serializable {
    /**
     * Database Column Remarks:
     *   用户主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   登陆名称(默认为手机号)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   登陆密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.login_password
     *
     * @mbg.generated
     */
    private String loginPassword;

    /**
     * Database Column Remarks:
     *   注册手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.login_mobile
     *
     * @mbg.generated
     */
    private String loginMobile;

    /**
     * Database Column Remarks:
     *   个性签名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.introduce_sign
     *
     * @mbg.generated
     */
    private String introduceSign;

    /**
     * Database Column Remarks:
     *   收件详细地址(街道/楼宇/单元)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     * Database Column Remarks:
     *   注销标识字段(0-正常 1-已注销)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   锁定标识字段(0-未锁定 1-已锁定)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.locked_flag
     *
     * @mbg.generated
     */
    private Byte lockedFlag;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_mall_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.user_id
     *
     * @return the value of t_insurance_mall_user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.user_id
     *
     * @param userId the value for t_insurance_mall_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.nick_name
     *
     * @return the value of t_insurance_mall_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.nick_name
     *
     * @param nickName the value for t_insurance_mall_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.login_name
     *
     * @return the value of t_insurance_mall_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.login_name
     *
     * @param loginName the value for t_insurance_mall_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.login_password
     *
     * @return the value of t_insurance_mall_user.login_password
     *
     * @mbg.generated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.login_password
     *
     * @param loginPassword the value for t_insurance_mall_user.login_password
     *
     * @mbg.generated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.login_mobile
     *
     * @return the value of t_insurance_mall_user.login_mobile
     *
     * @mbg.generated
     */
    public String getLoginMobile() {
        return loginMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.login_mobile
     *
     * @param loginMobile the value for t_insurance_mall_user.login_mobile
     *
     * @mbg.generated
     */
    public void setLoginMobile(String loginMobile) {
        this.loginMobile = loginMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.introduce_sign
     *
     * @return the value of t_insurance_mall_user.introduce_sign
     *
     * @mbg.generated
     */
    public String getIntroduceSign() {
        return introduceSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.introduce_sign
     *
     * @param introduceSign the value for t_insurance_mall_user.introduce_sign
     *
     * @mbg.generated
     */
    public void setIntroduceSign(String introduceSign) {
        this.introduceSign = introduceSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.user_address
     *
     * @return the value of t_insurance_mall_user.user_address
     *
     * @mbg.generated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.user_address
     *
     * @param userAddress the value for t_insurance_mall_user.user_address
     *
     * @mbg.generated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.is_deleted
     *
     * @return the value of t_insurance_mall_user.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.is_deleted
     *
     * @param isDeleted the value for t_insurance_mall_user.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.locked_flag
     *
     * @return the value of t_insurance_mall_user.locked_flag
     *
     * @mbg.generated
     */
    public Byte getLockedFlag() {
        return lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.locked_flag
     *
     * @param lockedFlag the value for t_insurance_mall_user.locked_flag
     *
     * @mbg.generated
     */
    public void setLockedFlag(Byte lockedFlag) {
        this.lockedFlag = lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_user.create_time
     *
     * @return the value of t_insurance_mall_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_user.create_time
     *
     * @param createTime the value for t_insurance_mall_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}