package com.sjy.insurance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_mall_goods_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Goods implements Serializable {
    /**
     * Database Column Remarks:
     *   保险商品表主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     * Database Column Remarks:
     *   保险商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     * Database Column Remarks:
     *   保险商品简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_intro
     *
     * @mbg.generated
     */
    private String goodsIntro;

    /**
     * Database Column Remarks:
     *   关联分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_category_id
     *
     * @mbg.generated
     */
    private Integer goodsCategoryId;

    /**
     * Database Column Remarks:
     *   保险商品主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_cover_img
     *
     * @mbg.generated
     */
    private String goodsCoverImg;

    /**
     * Database Column Remarks:
     *   保险商品轮播图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_carousel
     *
     * @mbg.generated
     */
    private String goodsCarousel;

    /**
     * Database Column Remarks:
     *   保险商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.original_price
     *
     * @mbg.generated
     */
    private Integer originalPrice;

    /**
     * Database Column Remarks:
     *   保险商品实际售价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.selling_price
     *
     * @mbg.generated
     */
    private Integer sellingPrice;

    private Integer claimAmount;

    private String deadline;

    /**
     * Database Column Remarks:
     *   保险商品标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * Database Column Remarks:
     *   保险商品上架状态 1-下架 0-上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_sell_status
     *
     * @mbg.generated
     */
    private Byte goodsSellStatus;

    /**
     * Database Column Remarks:
     *   添加者主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   保险商品添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改者主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   保险商品修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   保险商品详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_goods_info.goods_detail_content
     *
     * @mbg.generated
     */
    private String goodsDetailContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_mall_goods_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_id
     *
     * @return the value of t_insurance_mall_goods_info.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_id
     *
     * @param goodsId the value for t_insurance_mall_goods_info.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_name
     *
     * @return the value of t_insurance_mall_goods_info.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_name
     *
     * @param goodsName the value for t_insurance_mall_goods_info.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_intro
     *
     * @return the value of t_insurance_mall_goods_info.goods_intro
     *
     * @mbg.generated
     */
    public String getGoodsIntro() {
        return goodsIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_intro
     *
     * @param goodsIntro the value for t_insurance_mall_goods_info.goods_intro
     *
     * @mbg.generated
     */
    public void setGoodsIntro(String goodsIntro) {
        this.goodsIntro = goodsIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_category_id
     *
     * @return the value of t_insurance_mall_goods_info.goods_category_id
     *
     * @mbg.generated
     */
    public Integer getGoodsCategoryId() {
        return goodsCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_category_id
     *
     * @param goodsCategoryId the value for t_insurance_mall_goods_info.goods_category_id
     *
     * @mbg.generated
     */
    public void setGoodsCategoryId(Integer goodsCategoryId) {
        this.goodsCategoryId = goodsCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_cover_img
     *
     * @return the value of t_insurance_mall_goods_info.goods_cover_img
     *
     * @mbg.generated
     */
    public String getGoodsCoverImg() {
        return goodsCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_cover_img
     *
     * @param goodsCoverImg the value for t_insurance_mall_goods_info.goods_cover_img
     *
     * @mbg.generated
     */
    public void setGoodsCoverImg(String goodsCoverImg) {
        this.goodsCoverImg = goodsCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_carousel
     *
     * @return the value of t_insurance_mall_goods_info.goods_carousel
     *
     * @mbg.generated
     */
    public String getGoodsCarousel() {
        return goodsCarousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_carousel
     *
     * @param goodsCarousel the value for t_insurance_mall_goods_info.goods_carousel
     *
     * @mbg.generated
     */
    public void setGoodsCarousel(String goodsCarousel) {
        this.goodsCarousel = goodsCarousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.original_price
     *
     * @return the value of t_insurance_mall_goods_info.original_price
     *
     * @mbg.generated
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.original_price
     *
     * @param originalPrice the value for t_insurance_mall_goods_info.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.selling_price
     *
     * @return the value of t_insurance_mall_goods_info.selling_price
     *
     * @mbg.generated
     */
    public Integer getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.selling_price
     *
     * @param sellingPrice the value for t_insurance_mall_goods_info.selling_price
     *
     * @mbg.generated
     */
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.tag
     *
     * @return the value of t_insurance_mall_goods_info.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.tag
     *
     * @param tag the value for t_insurance_mall_goods_info.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_sell_status
     *
     * @return the value of t_insurance_mall_goods_info.goods_sell_status
     *
     * @mbg.generated
     */
    public Byte getGoodsSellStatus() {
        return goodsSellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_sell_status
     *
     * @param goodsSellStatus the value for t_insurance_mall_goods_info.goods_sell_status
     *
     * @mbg.generated
     */
    public void setGoodsSellStatus(Byte goodsSellStatus) {
        this.goodsSellStatus = goodsSellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.create_user
     *
     * @return the value of t_insurance_mall_goods_info.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.create_user
     *
     * @param createUser the value for t_insurance_mall_goods_info.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.create_time
     *
     * @return the value of t_insurance_mall_goods_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.create_time
     *
     * @param createTime the value for t_insurance_mall_goods_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.update_user
     *
     * @return the value of t_insurance_mall_goods_info.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.update_user
     *
     * @param updateUser the value for t_insurance_mall_goods_info.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.update_time
     *
     * @return the value of t_insurance_mall_goods_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.update_time
     *
     * @param updateTime the value for t_insurance_mall_goods_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_goods_info.goods_detail_content
     *
     * @return the value of t_insurance_mall_goods_info.goods_detail_content
     *
     * @mbg.generated
     */
    public String getGoodsDetailContent() {
        return goodsDetailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_goods_info.goods_detail_content
     *
     * @param goodsDetailContent the value for t_insurance_mall_goods_info.goods_detail_content
     *
     * @mbg.generated
     */
    public void setGoodsDetailContent(String goodsDetailContent) {
        this.goodsDetailContent = goodsDetailContent;
    }

    public Integer getClaimAmount() {
        return claimAmount;
    }

    public void setClaimAmount(Integer claimAmount) {
        this.claimAmount = claimAmount;
    }

    public String getDeadline() {
        return deadline;
    }

    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }
}