package com.sjy.insurance.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_guarantee_tmp
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GuaranteeTmp implements Serializable {
    /**
     * Database Column Remarks:
     *   商品名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_guarantee_tmp.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     * Database Column Remarks:
     *   商品总量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_guarantee_tmp.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_guarantee_tmp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_guarantee_tmp.goods_name
     *
     * @return the value of t_insurance_guarantee_tmp.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_guarantee_tmp.goods_name
     *
     * @param goodsName the value for t_insurance_guarantee_tmp.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_guarantee_tmp.total
     *
     * @return the value of t_insurance_guarantee_tmp.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_guarantee_tmp.total
     *
     * @param total the value for t_insurance_guarantee_tmp.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }
}