package com.sjy.insurance.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_insurer
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Insurer implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   保单名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.id_no
     *
     * @mbg.generated
     */
    private String idNo;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   职业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.career
     *
     * @mbg.generated
     */
    private String career;

    /**
     * Database Column Remarks:
     *   保单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.guarantee_no
     *
     * @mbg.generated
     */
    private String guaranteeNo;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   身高
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.height
     *
     * @mbg.generated
     */
    private Double height;

    /**
     * Database Column Remarks:
     *   体重
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     * Database Column Remarks:
     *   所属账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_insurer.belong_acc
     *
     * @mbg.generated
     */
    private String belongAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_insurer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.id
     *
     * @return the value of t_insurance_insurer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.id
     *
     * @param id the value for t_insurance_insurer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.name
     *
     * @return the value of t_insurance_insurer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.name
     *
     * @param name the value for t_insurance_insurer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.id_no
     *
     * @return the value of t_insurance_insurer.id_no
     *
     * @mbg.generated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.id_no
     *
     * @param idNo the value for t_insurance_insurer.id_no
     *
     * @mbg.generated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.age
     *
     * @return the value of t_insurance_insurer.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.age
     *
     * @param age the value for t_insurance_insurer.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.career
     *
     * @return the value of t_insurance_insurer.career
     *
     * @mbg.generated
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.career
     *
     * @param career the value for t_insurance_insurer.career
     *
     * @mbg.generated
     */
    public void setCareer(String career) {
        this.career = career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.guarantee_no
     *
     * @return the value of t_insurance_insurer.guarantee_no
     *
     * @mbg.generated
     */
    public String getGuaranteeNo() {
        return guaranteeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.guarantee_no
     *
     * @param guaranteeNo the value for t_insurance_insurer.guarantee_no
     *
     * @mbg.generated
     */
    public void setGuaranteeNo(String guaranteeNo) {
        this.guaranteeNo = guaranteeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.mobile
     *
     * @return the value of t_insurance_insurer.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.mobile
     *
     * @param mobile the value for t_insurance_insurer.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.email
     *
     * @return the value of t_insurance_insurer.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.email
     *
     * @param email the value for t_insurance_insurer.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.address
     *
     * @return the value of t_insurance_insurer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.address
     *
     * @param address the value for t_insurance_insurer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.height
     *
     * @return the value of t_insurance_insurer.height
     *
     * @mbg.generated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.height
     *
     * @param height the value for t_insurance_insurer.height
     *
     * @mbg.generated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.weight
     *
     * @return the value of t_insurance_insurer.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.weight
     *
     * @param weight the value for t_insurance_insurer.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_insurer.belong_acc
     *
     * @return the value of t_insurance_insurer.belong_acc
     *
     * @mbg.generated
     */
    public String getBelongAcc() {
        return belongAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_insurer.belong_acc
     *
     * @param belongAcc the value for t_insurance_insurer.belong_acc
     *
     * @mbg.generated
     */
    public void setBelongAcc(String belongAcc) {
        this.belongAcc = belongAcc;
    }
}