package com.sjy.insurance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   第三方公司账号表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_mall_thirdparty
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ThirdParty implements Serializable {
    /**
     * Database Column Remarks:
     *   第三方公司id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.seller_user_id
     *
     * @mbg.generated
     */
    private Integer sellerUserId;

    /**
     * Database Column Remarks:
     *   第三方公司登陆名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   第三方公司登陆密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.login_password
     *
     * @mbg.generated
     */
    private String loginPassword;

    /**
     * Database Column Remarks:
     *   第三方公司显示昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   注册手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.login_mobile
     *
     * @mbg.generated
     */
    private String loginMobile;

    /**
     * Database Column Remarks:
     *   注销标识字段(0-正常 1-已注销)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   是否锁定 0未锁定 1已锁定无法登陆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.locked
     *
     * @mbg.generated
     */
    private Byte locked;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_mall_thirdparty.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_mall_thirdparty
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.seller_user_id
     *
     * @return the value of t_insurance_mall_thirdparty.seller_user_id
     *
     * @mbg.generated
     */
    public Integer getSellerUserId() {
        return sellerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.seller_user_id
     *
     * @param sellerUserId the value for t_insurance_mall_thirdparty.seller_user_id
     *
     * @mbg.generated
     */
    public void setSellerUserId(Integer sellerUserId) {
        this.sellerUserId = sellerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.login_name
     *
     * @return the value of t_insurance_mall_thirdparty.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.login_name
     *
     * @param loginName the value for t_insurance_mall_thirdparty.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.login_password
     *
     * @return the value of t_insurance_mall_thirdparty.login_password
     *
     * @mbg.generated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.login_password
     *
     * @param loginPassword the value for t_insurance_mall_thirdparty.login_password
     *
     * @mbg.generated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.nick_name
     *
     * @return the value of t_insurance_mall_thirdparty.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.nick_name
     *
     * @param nickName the value for t_insurance_mall_thirdparty.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.login_mobile
     *
     * @return the value of t_insurance_mall_thirdparty.login_mobile
     *
     * @mbg.generated
     */
    public String getLoginMobile() {
        return loginMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.login_mobile
     *
     * @param loginMobile the value for t_insurance_mall_thirdparty.login_mobile
     *
     * @mbg.generated
     */
    public void setLoginMobile(String loginMobile) {
        this.loginMobile = loginMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.is_deleted
     *
     * @return the value of t_insurance_mall_thirdparty.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.is_deleted
     *
     * @param isDeleted the value for t_insurance_mall_thirdparty.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.locked
     *
     * @return the value of t_insurance_mall_thirdparty.locked
     *
     * @mbg.generated
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.locked
     *
     * @param locked the value for t_insurance_mall_thirdparty.locked
     *
     * @mbg.generated
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_mall_thirdparty.create_time
     *
     * @return the value of t_insurance_mall_thirdparty.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_mall_thirdparty.create_time
     *
     * @param createTime the value for t_insurance_mall_thirdparty.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}