package com.sjy.insurance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_insurance_topline
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TopLine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_topline.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_topline.message_title
     *
     * @mbg.generated
     */
    private String messageTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_topline.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_topline.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_insurance_topline.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_insurance_topline
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_topline.id
     *
     * @return the value of t_insurance_topline.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_topline.id
     *
     * @param id the value for t_insurance_topline.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_topline.message_title
     *
     * @return the value of t_insurance_topline.message_title
     *
     * @mbg.generated
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_topline.message_title
     *
     * @param messageTitle the value for t_insurance_topline.message_title
     *
     * @mbg.generated
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_topline.create_date
     *
     * @return the value of t_insurance_topline.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_topline.create_date
     *
     * @param createDate the value for t_insurance_topline.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_topline.create_user
     *
     * @return the value of t_insurance_topline.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_topline.create_user
     *
     * @param createUser the value for t_insurance_topline.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_insurance_topline.message_content
     *
     * @return the value of t_insurance_topline.message_content
     *
     * @mbg.generated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_insurance_topline.message_content
     *
     * @param messageContent the value for t_insurance_topline.message_content
     *
     * @mbg.generated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }
}